import csv


# 定义读取CSV文件并转换为集合的函数
def csv_to_set(file_path):
    data_set = set()
    with open(file_path, mode='r', encoding='utf-8') as file:
        reader = csv.reader(file)
        for row in reader:
            data_set.add(tuple(row))  # 将每一行转换为元组并存入集合
    return data_set


# 使用示例
file_path = 'docs/csvDocs/chuzhong.csv'  # 替换为你的CSV文件路径
data_set = csv_to_set(file_path)

# 打印结果
for item in data_set:
    print(item)

print(data_set)
print(len(data_set))

{('summer',), ('same',), ('driver',), ('be',), ('Russian',), ('discuss',), ('land',), ('celebrate',), ('teacher',),
 ('gold',), ('far',), ('smoke',), ('along',), ('Asia',), ('couple',), ('amazing',), ('local',), ('diet',), ('mall',),
 ('retire',), ('chicken',), ('baby',), ('snow',), ('soup',), ('away',), ('noon',), ('serious',), ('sleepy',),
 ('message',), ('some',), ('crayon',), ('baseball',), ('car',), ('steal',), ('afternoon',), ('yard',), ('creature',),
 ('lamb',), ('island',), ('string',), ('attention',), ('accent',), ('captain',), ('thrill',), ('hear',), ('drum',),
 ('thirtieth',), ('engineer',), ('eat',), ('steam',), ('brush',), ('knee',), ('remember',), ('upon',), ('permission',),
 ('difficult',), ('play',), ('top',), ('autumn',), ('position',), ('barbecue',), ('healthy',), ('offend',), ('record',),
 ('advice',), ('both',), ('language',), ('absent',), ('hen',), ('week',), ('lively',), ('cruel',), ('the',), ('world',),
 ('city',), ('useless',), ('no',), ('province',), ('zebra',), ('pretty',), ('balance',), ('dialogue',), ('soap',),
 ('them',), ('wake',), ('alien',), ('coat',), ('anymore',), ('sit',), ('club',), ('somewhere',), ('during',),
 ('scientist',), ('green',), ('telephone',), ('banana',), ('win',), ('quality',), ('work',), ('save',), ('birthday',),
 ('strong',), ('young',), ('teach',), ('left',), ('certain',), ('advise',), ('phone',), ('short',), ('stay',),
 ('scientific',), ('battery',), ('person',), ('address',), ('farmer',), ('dig',), ('modest',), ('legend',), ('cough',),
 ('brave',), ('speak',), ('advantage',), ('bow',), ('experience',), ('fail',), ('keep',), ('planet',), ('here',),
 ('meeting',), ('outgoing',), ('dry',), ('plastic',), ('catch',), ('hard',), ('doll',), ('classmate',), ('retell',),
 ('might',), ('railway',), ('happy',), ('mail',), ('usual',), ('nearby',), ('unit',), ('improve',), ('march',),
 ('eastern',), ('pierce',), ('father',), ('search',), ('tiger',), ('please',), ('drop',), ('recipe',), ('exam',),
 ('fifteenth',), ('theme',), ('ground',), ('north',), ('big',), ('firm',), ('building',), ('receive',), ('speaker',),
 ('waiter',), ('China',), ('plane',), ('study',), ('refuse',), ('kilometer',), ('shame',), ('simple',), ('boring',),
 ('cause',), ('plan',), ('total',), ('fifteen',), ('diary',), ('mark',), ('Monday',), ('feel',), ('frog',), ('clever',),
 ('pen',), ('drug',), ('thread',), ('birth',), ('my',), ('earth',), ('increase',), ('steel',), ('enough',), ('spend',),
 ('silly',), ('hot',), ('body',), ('international',), ('hunger',), ('always',), ('clock',), ('miss',), ('match',),
 ('rubber',), ('loud',), ('southern',), ('space',), ('bottle',), ('by',), ('kangaroo',), ('sometimes',), ('flu',),
 ('change',), ('stomach',), ('serve',), ('cousin',), ('tasty',), ('send',), ('Europe',), ('throat',), ('two',),
 ('smooth',), ('achieve',), ('November',), ('handbag',), ('drawer',), ('bear',), ('fix',), ('especially',), ('a',),
 ('avoid',), ('mistake',), ('turn',), ('peel',), ('traditional',), ('murder',), ('sense',), ('front',), ('bridge',),
 ('myself',), ('custom',), ('whenever',), ('arrive',), ('live',), ('level',), ('cabbage',), ('chemistry',),
 ('weekend',), ('impolite',), ('hardly',), ('aid',), ('since',), ('shape',), ('eleventh',), ('fire',), ('ring',),
 ('situation',), ('with',), ('private',), ('guest',), ('riddle',), ('stranger',), ('none',), ('air',), ('tennis',),
 ('drink',), ('tree',), ('French',), ('album',), ('hurt',), ('inside',), ('September',), ('library',), ('year',),
 ('house',), ('paper',), ('temperature',), ('cool',), ('what',), ('moon',), ('homeland',), ('satisfy',), ('physics',),
 ('juice',), ('egg',), ('either',), ('fight',), ('five',), ('wrong',), ('host',), ('singer',), ('Yin',), ('swim',),
 ('awake',), ('service',), ('eraser',), ('furry',), ('sky',), ('compare',), ('coach',), ('snowy',), ('granny',),
 ('into',), ('flat',), ('through',), ('truth',), ('sun',), ('yesterday',), ('heel',), ('sock',), ('hey',), ('in',),
 ('full',), ('surprise',), ('army',), ('cloud',), ('entertainment',), ('pet',), ('bulb',), ('do',), ('collect',),
 ('prison',), ('hit',), ('excuse',), ('wheel',), ('list',), ('company',), ('major',), ('question',), ('visit',),
 ('ball',), ('pop',), ('nearly',), ('cola',), ('break',), ('it',), ('door',), ('difficulty',), ('clean',),
 ('Saturday',), ('tragedy',), ('step',), ('huge',), ('magazine',), ('raise',), ('action',), ('marry',), ('thin',),
 ('everything',), ('easy',), ('me',), ('worldwide',), ('bathroom',), ('who',), ('fair',), ('sea',), ('cotton',),
 ('review',), ('active',), ('latest',), ('chair',), ('ugly',), ('school',), ('fever',), ('impossible',), ('kid',),
 ('bright',), ('rest',), ('fry',), ('suggestion',), ('license',), ('say',), ('scene',), ('adult',), ('coke',),
 ('pleasure',), ('trust',), ('skill',), ('schoolwork',), ('care',), ('those',), ('package',), ('once',), ('hotel',),
 ('luck',), ('bowl',), ('pilot',), ('able',), ('polite',), ('make',), ('dumpling',), ('scarf',), ('law',), ('still',),
 ('outside',), ('beard',), ('wife',), ('teen',), ('nine',), ('turtle',), ('polar',), ('under',), ('cage',), ('mouse',),
 ('punish',), ('tutor',), ('Sunday',), ('better',), ('cancer',), ('invent',), ('tale',), ('ton',), ('fifty',),
 ('subway',), ('disappointing',), ('translate',), ('college',), ('ninety',), ('tenth',), ('face',), ('smart',),
 ('order',), ('move',), ('besides',), ('biscuit',), ('copy',), ('think',), ('nurse',), ('elevator',), ('European',),
 ('upset',), ('great',), ('tail',), ('lot',), ('test',), ('square',), ('post',), ('end',), ('state',), ('dog',),
 ('manage',), ('coal',), ('I',), ('fit',), ('voice',), ('love',), ('bottom',), ('weigh',), ('fetch',), ('dentist',),
 ('party',), ('extra',), ('delicious',), ('cinema',), ('regular',), ('tie',), ('winter',), ('chopsticks',),
 ('conference',), ('wolf',), ('feed',), ('may',), ('write',), ('ride',), ('brother',), ('monster',), ('pull',),
 ('eighteen',), ('when',), ('online',), ('war',), ('seal',), ('wonderful',), ('find',), ('thirsty',), ('poster',),
 ('about',), ('importance',), ('research',), ('owner',), ('successful',), ('read',), ('motorcycle',), ('group',),
 ('meal',), ('thousand',), ('Miss',), ('cap',), ('almost',), ('rush',), ('white',), ('let',), ('tomato',), ('matter',),
 ('cat',), ('hide',), ('worst',), ('solution',), ('sugar',), ('pink',), ('instrument',), ('cancel',), ('also',),
 ('slide',), ('tired',), ('carry',), ('frustrate',), ('begin',), ('sheep',), ('discovery',), ('problem',), ('social',),
 ('hat',), ('symphony',), ('rock',), ('friendship',), ('apple',), ('June',), ('present',), ('throw',), ('finish',),
 ('Yang',), ('lesson',), ('not',), ('borrow',), ('toothbrush',), ('solid',), ('even',), ('to',), ('mention',),
 ('proud',), ('fifth',), ('holiday',), ('case',), ('lie',), ('disease',), ('lamp',), ('exchange',), ('August',),
 ('stream',), ('hallway',), ('hobby',), ('come',), ('dare',), ('excellent',), ('corner',), ('honey',), ('leaf',),
 ('station',), ('supply',), ('special',), ('till',), ('town',), ('tonight',), ('metal',), ('wide',), ('anybody',),
 ('student',), ('twentieth',), ('die',), ('color',), ('hall',), ('own',), ('machine',), ('yourselves',), ('later',),
 ('honor',), ('dull',), ('busy',), ('medal',), ('fourteenth',), ('jump',), ('spoken',), ('television',),
 ('understand',), ('common',), ('anxious',), ('swimming',), ('helicopter',), ('product',), ('bill',), ('sixty',),
 ('warm',), ('cake',), ('street',), ('violin',), ('pie',), ('allow',), ('opinion',), ('dad',), ('vocabulary',),
 ('class',), ('back',), ('gentleman',), ('three',), ('photo',), ('foreigner',), ('time',), ('negative',), ('market',),
 ('term',), ('sorry',), ('everybody',), ('gate',), ('cold',), ('unusual',), ('fox',), ('duty',), ('late',), ('leave',),
 ('clothes',), ('high',), ('brown',), ('ink',), ('medium',), ('Friday',), ('become',), ('team',), ('rat',), ('word',),
 ('cute',), ('trash',), ('nothing',), ('display',), ('sweep',), ('stress',), ('or',), ('lap',), ('walk',), ('cheap',),
 ('never',), ('our',), ('unhappy',), ('comment',), ('verb',), ('clear',), ('us',), ('stick',), ('spider',), ('little',),
 ('kill',), ('India',), ('monitor',), ('alright',), ('butter',), ('camp',), ('sentence',), ('elbow',), ('educate',),
 ('fact',), ('beautiful',), ('American',), ('fence',), ('nobody',), ('possibly',), ('coin',), ('choice',), ('am',),
 ('yourself',), ('season',), ('check',), ('point',), ('fourth',), ('example',), ('illness',), ('impress',),
 ('cigarette',), ('rather',), ('pacific',), ('airport',), ('grass',), ('knowledge',), ('wet',), ('jacket',),
 ('careless',), ('control',), ('show',), ('page',), ('watermelon',), ('honest',), ('lucky',), ('food',), ('theater',),
 ('other',), ('enter',), ('itself',), ('attendant',), ('article',), ('support',), ('toothpaste',), ('look',),
 ('screen',), ('pollution',), ('above',), ('seldom',), ('weather',), ('neck',), ('zero',), ('share',), ('agree',),
 ('offer',), ('postman',), ('travel',), ('yogurt',), ('standard',), ('pride',), ('line',), ('training',), ('hometown',),
 ('popularity',), ('warn',), ('guard',), ('hurry',), ('text',), ('fan',), ('hill',), ('treatment',), ('outstanding',),
 ('farm',), ('personal',), ('plant',), ('dangerous',), ('now',), ('terrorist',), ('sad',), ('long',), ('interesting',),
 ('decision',), ('overseas',), ('topic',), ('spread',), ('cheat',), ('most',), ('get',), ('there',), ('remain',),
 ('onion',), ('so',), ('blank',), ('happen',), ('every',), ('cup',), ('spell',), ('spoon',), ('behave',), ('dream',),
 ('intention',), ('way',), ('among',), ('chocolate',), ('sport',), ('umbrella',), ('reply',), ('print',), ('soft',),
 ('ill',), ('grandparent',), ('artist',), ('bee',), ('repeat',), ('use',), ('direct',), ('however',), ('ten',),
 ('sleep',), ('separate',), ('gym',), ('gallery',), ('spirit',), ('eighty',), ('smell',), ('hate',), ('key',),
 ('blow',), ('hello',), ('crazy',), ('Thursday',), ('until',), ('minute',), ('bank',), ('should',), ('development',),
 ('video',), ('yes',), ('player',), ('everyday',), ('follow',), ('granddaughter',), ('January',), ('and',), ('expect',),
 ('knock',), ('you',), ('could',), ('whole',), ('today',), ('aloud',), ('silent',), ('chew',), ('new',), ('which',),
 ('similar',), ('passport',), ('river',), ('rich',), ('prisoner',), ('poem',), ('risk',), ('February',), ('wealth',),
 ('lose',), ('need',), ('London',), ('believe',), ('refrigerator',), ('geography',), ('fisherman',), ('adverb',),
 ('fax',), ('blood',), ('homework',), ('Africa',), ('they',), ('professional',), ('medical',), ('off',), ('perfect',),
 ('con',), ('forbid',), ('fill',), ('forward',), ('difference',), ('song',), ('whose',), ('wood',), ('hum',),
 ('teenager',), ('queue',), ('imagine',), ('disturb',), ('expensive',), ('unpleasant',), ('rice',), ('fold',),
 ('avenue',), ('pig',), ('wild',), ('math',), ('film',), ('angry',), ('appointment',), ('single',), ('glad',),
 ('tooth',), ('then',), ('yet',), ('concert',), ('gentle',), ('elementary',), ('twice',), ('milk',), ('knife',),
 ('treat',), ('tiny',), ('sausage',), ('early',), ('hold',), ('last',), ('root',), ('woman',), ('rapid',), ('monkey',),
 ('sixteen',), ('realize',), ('leader',), ('just',), ('final',), ('reveal',), ('he',), ('if',), ('cent',), ('field',),
 ('prefer',), ('strawberry',), ('electric',), ('success',), ('book',), ('cry',), ('centre',), ('help',), ('normal',),
 ('disadvantage',), ('spot',), ('worse',), ('thank',), ('patient',), ('effort',), ('thirteenth',), ('lookout',),
 ('positive',), ('competition',), ('department',), ('invention',), ('escape',), ('noise',), ('kick',), ('except',),
 ('rocket',), ('nineteenth',), ('job',), ('accident',), ('prepare',), ('dormitory',), ('can',), ('indoors',), ('at',),
 ('art',), ('path',), ('fruit',), ('insist',), ('bird',), ('start',), ('destroy',), ('circle',), ('bread',), ('chase',),
 ('clone',), ('though',), ('suitable',), ('proper',), ('Wednesday',), ('assistant',), ('shut',), ('pretend',),
 ('capital',), ('rise',), ('breathe',), ('second',), ('explain',), ('mysterious',), ('discussion',), ('pressure',),
 ('university',), ('trousers',), ('room',), ('hour',), ('garden',), ('character',), ('seven',), ('saying',),
 ('therefore',), ('mend',), ('race',), ('seventy',), ('himself',), ('tongue',), ('festival',), ('talk',),
 ('volunteer',), ('return',), ('depend',), ('influence',), ('singular',), ('one',), ('goal',), ('pity',), ('jeans',),
 ('newspaper',), ('attitude',), ('reason',), ('conversation',), ('ancient',), ('run',), ('fourteen',), ('obey',),
 ('meaning',), ('only',), ('third',), ('misleading',), ('neighbor',), ('sight',), ('realistic',), ('salad',), ('arm',),
 ('hers',), ('predict',), ('penny',), ('skin',), ('master',), ('bell',), ('low',), ('belt',), ('shelf',), ('route',),
 ('deaf',), ('safety',), ('have',), ('enjoy',), ('tourist',), ('unless',), ('unimportant',), ('like',), ('calendar',),
 ('vehicle',), ('bitter',), ('comedy',), ('after',), ('anything',), ('safe',), ('ceiling',), ('everywhere',), ('goat',),
 ('succeed',), ('blackboard',), ('stone',), ('people',), ('garage',), ('servant',), ('want',), ('meter',), ('forty',),
 ('alone',), ('notice',), ('passage',), ('value',), ('elder',), ('slipper',), ('Tuesday',), ('hospital',),
 ('champion',), ('uniform',), ('chest',), ('lion',), ('attempt',), ('friend',), ('dictionary',), ('website',),
 ('documentary',), ('poor',), ('speed',), ('suggest',), ('Internet',), ('design',), ('life',), ('near',), ('brain',),
 ('perhaps',), ('slow',), ('sixteenth',), ('everyone',), ('joke',), ('disabled',), ('grandson',), ('row',), ('bother',),
 ('x-ray',), ('useful',), ('strange',), ('sure',), ('queen',), ('nice',), ('supermarket',), ('toy',), ('candle',),
 ('god',), ('litter',), ('palace',), ('shop',), ('animal',), ('twin',), ('mountain',), ('six',), ('south',),
 ('health',), ('give',), ('adj.',), ('May',), ('confident',), ('without',), ('camera',), ('cut',), ('connect',),
 ('friendly',), ('boss',), ('marriage',), ('know',), ('result',), ('shiny',), ('recorder',), ('Australian',),
 ('represent',), ('Mr.',), ('orange',), ('tea',), ('passenger',), ('day',), ('spare',), ('lake',), ('than',),
 ('activity',), ('feeling',), ('right',), ('unable',), ('quick',), ('instead',), ('swing',), ('statement',),
 ('calculator',), ('whatever',), ('October',), ('aggressive',), ('ice',), ('tool',), ('waste',), ('chore',), ('tall',),
 ('lead',), ('several',), ('worth',), ('possible',), ('stupid',), ('partner',), ('sweater',), ('ninth',), ('solve',),
 ('important',), ('too',), ('encourage',), ('bush',), ('combine',), ('bag',), ('fish',), ('amount',), ('number',),
 ('shirt',), ('France',), ('nor',), ('whom',), ('thief',), ('earthquake',), ('symbol',), ('toilet',), ('enemy',),
 ('maths',), ('story',), ('chance',), ('general',), ('part',), ('famous',), ('view',), ('quiet',), ('sweet',),
 ('truck',), ('count',), ('money',), ('side',), ('radio',), ('sell',), ('see',), ('these',), ('fun',), ('semester',),
 ('towel',), ('infinitive',), ('tower',), ('pool',), ('flee',), ('introduce',), ('its',), ('prove',), ('purple',),
 ('dismiss',), ('background',), ('praise',), ('child',), ('sand',), ('found',), ('basket',), ('for',), ('deep',),
 ('dress',), ('complain',), ('coffee',), ('convenient',), ('sale',), ('beat',), ('oak',), ('yellow',), ('country',),
 ('down',), ('toast',), ('strategy',), ('turkey',), ('condition',), ('twenty',), ('height',), ('dish',), ('nineteen',),
 ('kilo',), ('well',), ('skate',), ('buy',), ('lab',), ('fantastic',), ('first',), ('hole',), ('Mars',), ('around',),
 ('drive',), ('Paris',), ('yoghurt',), ('answer',), ('mirror',), ('score',), ('Atlantic',), ('twelve',), ('area',),
 ('America',), ('writer',), ('east',), ('note',), ('injure',), ('already',), ('boil',), ('million',), ('rope',),
 ('west',), ('leg',), ('price',), ('wave',), ('western',), ('fiction',), ('dinner',), ('protect',), ('him',), ('how',),
 ('freeze',), ('jungle',), ('pioneer',), ('recent',), ('anywhere',), ('someone',), ('thought',), ('silk',), ('nature',),
 ('TRUE',), ('behind',), ('England',), ('pocket',), ('will',), ('breath',), ('month',), ('instance',), ('pair',),
 ('sir',), ('airplane',), ('ear',), ('another',), ('chess',), ('least',), ('secret',), ('autograph',), ('progress',),
 ('casually',), ('establish',), ('wise',), ('accept',), ('shoulder',), ('piano',), ('used',), ('eight',), ('rabbit',),
 ('\ufeff初中',), ('northern',), ('candy',), ('tour',), ('seat',), ('mom',), ('mystery',), ('beauty',), ('robot',),
 ('somebody',), ('keyboard',), ('shark',), ('pain',), ('develop',), ('cheer',), ('sofa',), ('style',), ('dislike',),
 ('slice',), ('modern',), ('eye',), ('inch',), ('visitor',), ('window',), ('piece',), ('black',), ('careful',),
 ('mine',), ('girlfriend',), ('rank',), ('loving',), ('district',), ('next',), ('floor',), ('edge',), ('decide',),
 ('free',), ('nervous',), ('best',), ('dozen',), ('original',), ('mind',), ('popular',), ('gift',), ('sixth',),
 ('housework',), ('restaurant',), ('deal',), ('ham',), ('noodle',), ('tape',), ('fashion',), ('card',), ('laboratory',),
 ('asleep',), ('lunch',), ('hundred',), ('join',), ('bookcase',), ('pardon',), ('relax',), ('pork',), ('computer',),
 ('ours',), ('accessory',), ('trade',), ('notebook',), ('pack',), ('authority',), ('grammar',), ('menu',), ('sing',),
 ('band',), ('cookie',), ('up',), ('mess',), ('association',), ('worker',), ('court',), ('climb',), ('cover',),
 ('volleyball',), ('cream',), ('degree',), ('half',), ('glove',), ('essay',), ('staff',), ('wound',), ('rent',),
 ('outdoor',), ('light',), ('president',), ('reach',), ('ache',), ('soccer',), ('twelfth',), ('sour',), ('music',),
 ('purpose',), ('straight',), ('upstairs',), ('as',), ('rose',), ('much',), ('wheat',), ('toward',), ('treasure',),
 ('snake',), ('parent',), ('future',), ('fork',), ('communicate',), ('kitchen',), ('toothache',), ('humorous',),
 ('storm',), ('sandwich',), ('madam',), ('VCD',), ('traffic',), ('grade',), ('fast',), ('memory',), ('boat',),
 ('wallet',), ('else',), ('lighting',), ('laugh',), ('stamp',), ('human',), ('operation',), ('hair',), ('duck',),
 ('more',), ('moment',), ('against',), ('period',), ('village',), ('seem',), ('welcome',), ('express',), ('that',),
 ('real',), ('is',), ('emotion',), ('pleasant',), ('biology',), ('night',), ('complete',), ('cow',), ('hungry',),
 ('handsome',), ('introduction',), ('require',), ('southeast',), ('themselves',), ('flower',), ('photograph',),
 ('forget',), ('escalator',), ('communication',), ('include',), ('really',), ('ocean',), ('home',), ('rule',),
 ('December',), ('recite',), ('burn',), ('interest',), ('spring',), ('fine',), ('watch',), ('rural',), ('rain',),
 ('eighteenth',), ('jazz',), ('energy',), ('create',), ('fool',), ('suppose',), ('parrot',), ('promise',), ('morning',),
 ('hang',), ('prevent',), ('member',), ('bike',), ('choose',), ('July',), ('silver',), ('shout',), ('classroom',),
 ('report',), ('information',), ('comfortable',), ('chip',), ('resolution',), ('available',), ('bicycle',), ('few',),
 ('overcoat',), ('ready',), ('ruler',), ('golden',), ('lost',), ('particular',), ('bamboo',), ('pear',), ('hero',),
 ('small',), ('mother',), ('structure',), ('zigzag',), ('keen',), ('distance',), ('tell',), ('anyway',), ('homeless',),
 ('Indian',), ('stage',), ('surface',), ('many',), ('operate',), ('large',), ('seek',), ('weak',), ('press',),
 ('phrase',), ('listen',), ('this',), ('breakfast',), ('fridge',), ('practice',), ('an',), ('sound',), ('pupil',),
 ('oneself',), ('specific',), ('fall',), ('stop',), ('size',), ('cook',), ('act',), ('middle',), ('bring',),
 ('technology',), ('all',), ('conjunction',), ('manner',), ('main',), ('environment',), ('wall',), ('trouble',),
 ('lifestyle',), ('shy',), ('neither',), ('she',), ('fresh',), ('favorite',), ('sauce',), ('yeah',), ('bed',),
 ('stair',), ('coast',), ('labor',), ('greeting',), ('doubt',), ('envelope',), ('English',), ('blue',), ('herself',),
 ('clerk',), ('basic',), ('invite',), ('sunny',), ('Jew',), ('kiss',), ('church',), ('subject',), ('Christmas',),
 ('rainy',), ('double',), ('restroom',), ('lonely',), ('immediately',), ('award',), ('touch',), ('glass',),
 ('picture',), ('popcorn',), ('plain',), ('project',), ('pro',), ('from',), ('less',), ('net',), ('appear',),
 ('course',), ('continue',), ('board',), ('train',), ('dear',), ('junk',), ('crowd',), ('unhealthy',), ('primary',),
 ('object',), ('ant',), ('taste',), ('composition',), ('talent',), ('dirty',), ('CD',), ('round',), ('downstairs',),
 ('awful',), ('silence',), ('quite',), ('population',), ('tomorrow',), ('wind',), ('sick',), ('past',), ('would',),
 ('peace',), ('government',), ('ticket',), ('suit',), ('countryside',), ('wear',), ('thirty',), ('consider',),
 ('prediction',), ('Russia',), ('heavy',), ('science',), ('eleven',), ('mad',), ('probably',), ('wait',), ('chalk',),
 ('material',), ('porridge',), ('chat',), ('super',), ('lovely',), ('hope',), ('divide',), ('seventh',), ('on',),
 ('Rusia',), ('chop',), ('wine',), ('daily',), ('soldier',), ('date',), ('very',), ('iron',), ('paint',),
 ('playground',), ('yours',), ('ship',), ('idea',), ('method',), ('son',), ('regret',), ('agreement',), ('shower',),
 ('pay',), ('doctor',), ('their',), ('concentrate',), ('relative',), ('joy',), ('road',), ('officer',), ('ago',),
 ('donate',), ('mean',), ('take',), ('costume',), ('headache',), ('table',), ('calm',), ('heart',), ('trip',), ('boy',),
 ('theatre',), ('star',), ('culture',), ('seventeen',), ('exhibition',), ('scared',), ('announce',), ('oil',),
 ('pronounce',), ('bad',), ('meet',), ('plenty',), ('build',), ('repair',), ('man',), ('any',), ('meat',),
 ('creative',), ('her',), ('discover',), ('relation',), ('danger',), ('smile',), ('age',), ('behaviour',), ('produce',),
 ('office',), ('are',), ('perform',), ('tidy',), ('abroad',), ('form',), ('advertisement',), ('specifically',),
 ('death',), ('unfriendly',), ('cheese',), ('lazy',), ('put',), ('heaven',), ('cupboard',), ('cost',), ('shock',),
 ('furniture',), ('seventeenth',), ('call',), ('your',), ('water',), ('history',), ('sudden',), ('nod',), ('weight',),
 ('instruction',), ('different',), ('rubbish',), ('cross',), ('stairs',), ('park',), ('while',), ('uncle',), ('role',),
 ('survey',), ('foreign',), ('thick',), ('spotlight',), ('nose',), ('eighth',), ('below',), ('potato',), ('wash',),
 ('open',), ('such',), ('Australia',), ('underground',), ('although',), ('shake',), ('over',), ('excite',), ('guess',),
 ('ability',), ('again',), ('insect',), ('king',), ('weekday',), ('scary',), ('center',), ('map',), ('Chinese',),
 ('football',), ('shoe',), ('victory',), ('wing',), ('picnic',), ('camel',), ('quarter',), ('born',), ('belong',),
 ('family',), ('task',), ('across',), ('socks',), ('raincoat',), ('national',), ('shall',), ('talented',), ('soon',),
 ('agent',), ('grape',), ('afford',), ('sink',), ('transportation',), ('ourselves',), ('must',), ('mile',), ('blind',),
 ('draw',), ('opposite',), ('shampoo',), ('dance',), ('add',), ('empty',), ('store',), ('supper',), ('helpful',),
 ('wonder',), ('fat',), ('push',), ('purse',), ('thirteen',), ('wish',), ('argue',), ('equipment',), ('provide',),
 ('horse',), ('Japanese',), ('girl',), ('flag',), ('criticize',), ('why',), ('correct',), ('musician',), ('comma',),
 ('head',), ('bit',), ('hand',), ('underwater',), ('model',), ('aunt',), ('thing',), ('lend',), ('together',),
 ('rude',), ('challenge',), ('beyond',), ('lemonade',), ('schoolbag',), ('basketball',), ('anyone',), ('balloon',),
 ('airline',), ('lady',), ('but',), ('butterfly',), ('necessary',), ('mouth',), ('daughter',), ('whale',),
 ('uncomfortable',), ('pencil',), ('policy',), ('interview',), ('mix',), ('tense',), ('lay',), ('often',), ('theirs',),
 ('clap',), ('gun',), ('out',), ('of',), ('cloudy',), ('pronunciation',), ('bye',), ('museum',), ('dead',),
 ('manager',), ('experiment',), ('regard',), ('medicine',), ('vegetable',), ('beef',), ('news',), ('his',), ('four',),
 ('marathon',), ('charity',), ('examine',), ('because',), ('Wheel',), ('try',), ('surf',), ('worry',), ('Brazilian',),
 ('OK',), ('chairman',), ('industry',), ('shine',), ('speech',), ('vacation',), ('cooker',), ('carrot',), ('finger',),
 ('force',), ('heat',), ('plate',), ('ever',), ('microwave',), ('aim',), ('program',), ('learn',), ('close',),
 ('sort',), ('stand',), ('bored',), ('etiquette',), ('tag',), ('specially',), ('Canada',), ('police',), ('panda',),
 ('native',), ('box',), ('factory',), ('unfamiliar',), ('tent',), ('pancake',), ('easily',), ('where',), ('courage',),
 ('clothing',), ('secretary',), ('funny',), ('pronoun',), ('organize',), ('kite',), ('beside',), ('suitcase',),
 ('alive',), ('opportunity',), ('sail',), ('strict',), ('husband',), ('hamburger',), ('old',), ('red',), ('prize',),
 ('shell',), ('dollar',), ('giraffe',), ('author',), ('letter',), ('society',), ('lift',), ('winner',), ('towards',),
 ('elephant',), ('salt',), ('border',), ('pound',), ('zoo',), ('bus',), ('ask',), ('grandchild',), ('each',),
 ('April',), ('education',), ('sister',), ('fear',), ('we',), ('percent',), ('evening',), ('pass',), ('skirt',),
 ('desk',), ('forest',), ('chant',), ('shorts',), ('set',), ('pick',), ('dessert',), ('embarrassed',), ('between',),
 ('public',), ('Asian',), ('maybe',), ('foot',), ('feature',), ('before',), ('dark',), ('shoot',), ('magic',),
 ('recycle',), ('beach',), ('describe',), ('place',), ('Japan',), ('whether',), ('fly',), ('movie',), ('taxi',),
 ('flight',), ('block',), ('kind',), ('exercise',), ('lock',), ('postcard',), ('something',), ('bedroom',),
 ('natural',), ('game',), ('opera',), ('century',), ('sign',), ('March',), ('business',), ('name',), ('windy',),
 ('afraid',), ('pour',), ('type',), ('pond',), ('terrible',)}
